name: Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Build
      - name: Build the file
        run: |
          ls /home/runner/work/
          cd /home/runner/work/melnor-bluetooth-ha/melnor-bluetooth-ha/custom_components/melnor
          zip -r melnor.zip *
      # Upload build file to the release as an asset
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/melnor-bluetooth-ha/melnor-bluetooth-ha/custom_components/melnor/melnor.zip
          asset_name: melnor.zip
          tag: ${{ github.ref }}
          overwrite: true